[package]
name = "tiny"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies.multiversx-sc-scenario]
version = "0.65.0"
path = "../../../framework/scenario"
features = ["wasmer-experimental"]
